# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

random_tensor1 = torch.rand(7, 7)
print(random_tensor1)


cuda
tensor([[0.4384, 0.3285, 0.9246, 0.6510, 0.3028, 0.3873, 0.8860],
        [0.7215, 0.4025, 0.0254, 0.3603, 0.1683, 0.4027, 0.1978],
        [0.9355, 0.6004, 0.7487, 0.5957, 0.0076, 0.2837, 0.6246],
        [0.9251, 0.8230, 0.0222, 0.4239, 0.6896, 0.6126, 0.3266],
        [0.5776, 0.2808, 0.9840, 0.2945, 0.9358, 0.8289, 0.8534],
        [0.2960, 0.7373, 0.2064, 0.5008, 0.1099, 0.1006, 0.2554],
        [0.7253, 0.2258, 0.6172, 0.1622, 0.8695, 0.9851, 0.1408]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
# Perform matrix multiplication 

random_tensor2 = torch.rand(1, 7)
result = random_tensor1 @ random_tensor2.T
print(result.shape)
print(result)
        
# print(torch.matmul(random_tensor1, random_tensor2))



torch.Size([7, 1])
tensor([[1.2301],
        [1.0895],
        [1.3483],
        [1.8513],
        [1.9981],
        [0.5761],
        [1.8318]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor1 = torch.rand(7, 7)
print(random_tensor1)
random_tensor2 = torch.rand(1, 7)
print(random_tensor2)
# Matrix multiply tensors
result = torch.matmul(random_tensor1, random_tensor2.T)
print(result)


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
gpu_seed = torch.cuda.manual_seed(1234)

None



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [28]:
# Set random seed
gpu_seed = torch.cuda.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

# Create two random tensors on GPU
gpu_random_tensor1 = torch.rand(2, 3, device = device)
gpu_random_tensor2 = torch.rand(2, 3, device = device)
print(gpu_random_tensor1)
print(gpu_random_tensor2)


cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [30]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(gpu_random_tensor1, gpu_random_tensor2.T)
print(result)
print(result.shape)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [34]:
print(result)
# Find max
max = result.max()
print(max)
# Find min
min = result.min()
print(min)


tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')
tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [36]:
print(result)
# Find arg max
argmax = result.argmax()
print(argmax)
# Find arg min
argmin = result.argmin()
print(argmin)


tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [39]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
random_tensor3 = torch.rand(1, 1, 1, 10, device = device)
print(random_tensor3)
print(random_tensor3.shape)

# Remove single dimensions
random_tensor3_squeezed = random_tensor3.squeeze()
print(random_tensor3_squeezed)
print(random_tensor3_squeezed.shape)

# Print out tensors and their shapes


tensor([[[[0.0807, 0.0306, 0.9396, 0.8597, 0.1281, 0.9946, 0.1527, 0.9944,
           0.1310, 0.4656]]]], device='cuda:0')
torch.Size([1, 1, 1, 10])
tensor([0.0807, 0.0306, 0.9396, 0.8597, 0.1281, 0.9946, 0.1527, 0.9944, 0.1310,
        0.4656], device='cuda:0')
torch.Size([10])
